#!/usr/bin/env bash
### 
###             v32as - Vircon32 assembler written in BASH, powered by
###                     Regular Expressions
### 
###              usage: v32as [OPTION..] ASMFILE.ASM
### 
###            option - description
### =================   ===================================================
###  outfile=FILE.OBJ   specify output OBJ file
###           verbose   increase verbosity
###              help   display usage information and exit
### 
### NOTE: It is meant for v32pp, the Vircon32 Assembly Pre-Processor, to be
### run prior to passing the code through this assembler. Furthermore,  for
### the production of an actual VBIN file, a further tool is required. This
### assembler will ONLY convert to machine code, and nothing more.
### 
########################################################################################

##############################################################################
##
## Process command-line arguments
##
DO_HELP=$(echo "${*}" | egrep -qio '\<help\>' && echo "true" || echo "false")
VERBOSE=$(echo "${*}" | egrep -qio '\<verbos' && echo "true" || echo "false")

##############################################################################
##
## Display usage information if requested (and exit)
##
[ "${DO_HELP}" = "true" ] && cat ${0} | grep '^### ' | tr -d '#' && exit 0

########################################################################################
##
## Declare and initialize variables
##
FLOATIFY="./floatify"

########################################################################################
##
## Establish RegEx patterns for tokens
##
OPCODE='\<(IN|JT|JF|OR|[A-Z][A-Z2]{2,4})\>'
INT_TWO_OPCODE="\<JT|JF|IEQ|INE|IGT|IGE|ILT|ILE|MOV|LEA|IN|OUT|AND|OR|XOR|SHL"
INT_TWO_OPCODE="${INT_TWO_OPCODE}|IADD|ISUB|IMUL|IDIV|IMOD|IMIN|IMAX\>"
FLOAT_TWO_OPCODE="\<FEQ|FNE|FGT|FGE|FLT|FLE|FADD"
FLOAT_TWO_OPCODE="${FLOAT_TWO_OPCODE}|FSUB|FMUL|FDIV|FMOD|FMIN|FMAX|ATAN2|POW\>"
REGISTER='\<(R[0-9]|R1[0-5]|BP|SP|CR|SR|DR)\>'
HEX1='\<0[Xx][0-9A-F]{1,8}\>'
HEX2='\<[0-9A-F]{1,8}[Hh]\>'
OCT='\<0[0-7]+\>'
BIN='\<0[Bb][01]{1,32}\>'
DEC1='\<[+-]?([0-9]|[1-9][0-9]*)\>'
DEC2='\<#[+-]?([0-9]|[1-9][0-9]*)\>'
# word boundaries not catching any signed values
# echo "MOV R5, +0" | tr ' ' '\n' | tr -s ' ' | egrep -o '^[-+]?([1-9]|[1-9][0-9]*)|[+]?0$'
FLOAT='\<[+-]?([0-9]\.[0-9][0-9]*|[1-9][0-9]*\.[0-9][0-9]*)\>'
IMMEDIATE="(${BIN}|${OCT}|${DEC1}|${DEC2}|${FLOAT}|${HEX1}|${HEX2})"
INDEX="[-+]"
INDEXED="${REGISTER}[-+]${IMMEDIATE}"
#DEREF="[[](${REGISTER}|${IMMEDIATE}|${INDEXED})[]]"
DEREF="[[].*[]]"
OPERAND="(${DEREF}|${REGISTER}|${IMMEDIATE})"
#OPERAND="[[]?(${REGISTER}|${IMMEDIATE}|${REGISTER}${INDEXED}${IMMEDIATE})[]]?"
ZERO_OPCODE='\<HLT|WAIT|RET|MOVS|SETS\>'
ONE_OPCODE="\<JMP|CALL|PUSH|POP|CMPS|CIF|CFI|CIB|CFB|NOT|BNOT|ISGN|IABS|FSGN|FABS"
ONE_OPCODE="${ONE_OPCODE}|FLR|CEIL|ROUND|SIN|ACOS|LOG\>"
ONE_BRANCH="\<JMP|CALL\>"
ZEROOPER="[^;]*${ZERO_OPCODE}"
ONE_OPER="[^;]*${ONE_OPCODE} *${OPERAND}"
TWO_OPER="[^;]*${INT_TWO_OPCODE} *${OPERAND} *, *${OPERAND}"

declare -A OTYPE
OTYPE["index"]="${INDEXED}"
OTYPE["deref"]="${DEREF}"
OTYPE["register"]="${REGISTER}"
OTYPE["immediate"]="${IMMEDIATE}"

declare -A ITYPE
ITYPE["hex"]="${HEX1}"
ITYPE["hex2"]="${HEX2}"
ITYPE["oct"]="${OCT}"
ITYPE["bin"]="${BIN}"
ITYPE["dec"]="${DEC1}"
ITYPE["dec2"]="${DEC2}"
ITYPE["float"]="${FLOAT}"

declare -a ONE_BRANCH
ONE_BRANCH[0]="${IMMEDIATE}"
ONE_BRANCH[1]="${REGISTER}"

declare -a ONE_PARAM
ONE_PARAM[0]="${REGISTER}"

declare -a TWO_PARAM
TWO_PARAM[0]="${REGISTER} *, *${IMMEDIATE}"
TWO_PARAM[1]="${REGISTER} *, *${REGISTER}"

########################################################################################
##
## MOV has 8 different addressing modes, described via RegEx here
##
declare -a MOV_PARAM
MOV_PARAM[0]="${REGISTER} *, *${IMMEDIATE}"
MOV_PARAM[1]="${REGISTER} *, *${REGISTER}"
MOV_PARAM[2]="${REGISTER} *, *[[]${IMMEDIATE}[]]"
MOV_PARAM[3]="${REGISTER} *, *[[]${REGISTER}[]]"
MOV_PARAM[4]="${REGISTER} *, *[[]${INDEXED}[]]"
MOV_PARAM[5]="[[]${IMMEDIATE}[]] *, *${REGISTER}"
MOV_PARAM[6]="[[]${REGISTER}[]] *, *${REGISTER}"
MOV_PARAM[7]="[[]${INDEXED}[]] *, *${REGISTER}"

declare -a LEA_PARAM
LEA_PARAM[0]="${REGISTER} *, *[[]${REGISTER}[]]"
LEA_PARAM[1]="${REGISTER} *, *[[]${INDEXED}[]]"

declare -a IN_PARAM
IN_PARAM[0]="${REGISTER} *, *${PORT}"

declare -a OUT_PARAM
OUT_PARAM[0]="${PORT} *, *${IMMEDIATE}"
OUT_PARAM[1]="${PORT} *, *${REGISTER}"

declare -a PTYPE
PTYPE[0]="${ZERO_OPCODE}"
PTYPE[1]="${ONE_OPCODE}"
PTYPE[2]="${INT_TWO_OPCODE}"
PTYPE[3]="${FLOAT_TWO_OPCODE}"

declare -A opcode
opcode["HLT"]="000000"
opcode["WAIT"]="000001"
opcode["JMP"]="000010"
opcode["CALL"]="000011"
opcode["RET"]="000100"
opcode["JT"]="000101"
opcode["JF"]="000110"
opcode["IEQ"]="000111"
opcode["INE"]="001000"
opcode["IGT"]="001001"
opcode["IGE"]="001010"
opcode["ILT"]="001011"
opcode["ILE"]="001100"
opcode["FEQ"]="001101"
opcode["FNE"]="001110"
opcode["FGT"]="001111"
opcode["FGE"]="010000"
opcode["FLT"]="010001"
opcode["FLE"]="010010"
opcode["MOV"]="010011"
opcode["LEA"]="010100"
opcode["PUSH"]="010101"
opcode["POP"]="010110"
opcode["IN"]="010111"
opcode["OUT"]="011000"
opcode["MOVS"]="011001"
opcode["SETS"]="011010"
opcode["CMPS"]="011011"
opcode["CIF"]="011100"
opcode["CFI"]="011101"
opcode["CIB"]="011110"
opcode["CFB"]="011111"
opcode["NOT"]="100000"
opcode["AND"]="100001"
opcode["OR"]="100010"
opcode["XOR"]="100011"
opcode["BNOT"]="100100"
opcode["SHL"]="100101"
opcode["IADD"]="100110"
opcode["ISUB"]="100111"
opcode["IMUL"]="101000"
opcode["IDIV"]="101001"
opcode["IMOD"]="101010"
opcode["ISGN"]="101011"
opcode["IMIN"]="101100"
opcode["IMAX"]="101101"
opcode["IABS"]="101110"
opcode["FADD"]="101111"
opcode["FSUB"]="110000"
opcode["FMUL"]="110001"
opcode["FDIV"]="110010"
opcode["FMOD"]="110011"
opcode["FSGN"]="110100"
opcode["FMIN"]="110101"
opcode["FMAX"]="110110"
opcode["FABS"]="110111"
opcode["FLR"]="111000"
opcode["CEIL"]="111001"
opcode["ROUND"]="111010"
opcode["SIN"]="111011"
opcode["ACOS"]="111100"
opcode["ATAN2"]="111101"
opcode["LOG"]="111110"
opcode["POW"]="111111"
IMM_TALLY=0
imm_flag=0

########################################################################################
##
## getregnum(): obtain numeric value of register
##
function getregnum()
{
	REG="${1}"
	case "${REG}" in
		"CR")
			VAL="1011"
			;;
		"SR")
			VAL="1100"
			;;
		"DR")
			VAL="1101"
			;;
		"BP")
			VAL="1110"
			;;
		"SP")
			VAL="1111"
			;;
		"IP")
			VAL="none"
			;;
		"IR")
			VAL="none"
			;;
		"IV")
			VAL="none"
			;;
		*)
			VAL=$(echo "${REG}" | tr -d 'A-Za-z:')
            VAL=$(echo "obase=2; ${VAL}" | bc -q)
            VAL=$(printf "%.4d" "${VAL}")
			;;
	esac
	echo "${VAL}"
}

########################################################################################
##
## parse_reg(): function to parse and return the register component from  the
##              provided token. Will ensure the returned value is using upper
##              case letters. Supports all the aliased registers.
##
function parse_reg()
{
    token="${1}"
    the_reg=$(echo "${token}" | egrep -o "${REGISTER}")
    echo "${the_reg}" | tr 'bcdspriv' 'BCDSPRIV'
}

########################################################################################
##
## parse_imm(): function to parse and convert immediate value to standard hex
##              representation, leading '0x', and 8 total digits. It converts
##              a number of recognized formats:
##
##              0bXXXX - binary value (1-32 bits)
##              0XXXX  - octal value
##              XXXX   - decimal value
##              #XXXX  - decimal value
##              0xXXXX - standard hexadecimal representation (the target)
##              XXXXH  - alternate hexadecimal representation
##              X.XXXX - floating point value
##
function parse_imm()
{
    token="${1}"
    for attr in bin oct dec1 dec2 hex hex2 float; do
        d_imm=$(echo "${token}"  | egrep -o "${ITYPE[${attr}]}")
        t_imm=$(echo "${token}"  | egrep -o "${ITYPE[${attr}]}" | wc -l)
#        echo "ITYPE: ${ITYPE[*]}" 1>&2
#        echo "d_imm: ${d_imm}" 1>&2
#        echo "t_imm: ${i_imm}" 1>&2
        if [ "${t_imm}" -eq 1 ]; then
            case "${attr}" in
                "bin")
                    d_imm=$(echo "${token}" | tr -d 'B' | tr -d 'b')
                    d_imm=$(echo "obase=16; ibase=2; ${d_imm}" | bc)
                    ;;

                "oct")
                    d_imm=$(echo "obase=16; ibase=8; ${d_imm}" | bc)
                    ;;

                "dec1")
                    d_imm=$(echo "obase=16; ibase=10; ${d_imm}" | bc)
                    ;;

                "dec2")
                    d_imm=$(echo "${token}" | tr -d '#')
                    d_imm=$(echo "obase=16; ibase=10; ${d_imm}" | bc)
                    ;;

                "hex")
                    d_imm=$(echo "${token}")
                    ;;

                "hex2")
                    d_imm=$(echo "${token}" | tr -d 'H')
                    ;;

                "float")
                    d_imm=$(${FLOATIFY} "${token}")
                    ;;
            esac
            d_imm=$(echo "${d_imm}"   | tr    'X' 'x' | cut -d'x' -f2)
            d_imm=$(printf "0x%8s" "${d_imm}" | tr ' ' '0')
            break
        fi
    done
    echo "${d_imm}"
}

function parse_operator()
{
    token="${1}"
    for attr in bin oct dec1 dec2 hex2; do
        p_data=$(echo "${token}"  | egrep -o "${ITYPE[${attr}]}")
        p_type=$(echo "${token}"  | egrep -o "${ITYPE[${attr}]}" | wc -l)
        if [ "${p_type}" -eq 1 ]; then
            case "${attr}" in
                "+")
                    ;;
                "-")
                    ;;
            esac
            p_data=$(echo "${p_data}"   | tr    'X' 'x' | cut -d'x' -f2)
            p_data=$(printf "0x%8s" "${p_data}" | tr ' ' '0')
            break
        fi
    done
    echo "${p_data}"

}

function parse_param()
{
    token="${1}"
    i_data=
    o_data=
    r_data=
    for attr in index deref register immediate; do
        p_data=$(echo "${token}"  | egrep -o "${OTYPE[${attr}]}")
        p_type=$(echo "${token}"  | egrep -o "${OTYPE[${attr}]}" | wc -l)

#        echo "attr: ${attr}, p_type: ${p_type}, p_data: ${p_data}" 1>&2
        if [ "${p_type}" -eq 1 ]; then
            case "${attr}" in
                "index")
                    token=$(echo  "${token}" | tr -d '[' | tr -d ']')
                    o_data=$(echo "${token}" | egrep -o "${INDEX}")
                    echo "o_data: ${o_data}" 1>&2
                    reg_t=$(echo  "${token}" | cut -d"${o_data}" -f1)
                    r_data=$(parse_reg "${reg_t}")
                    imm_t=$(echo  "${token}" | cut -d"${o_data}" -f2)
                    i_data=$(parse_imm "${imm_t}")
                    #echo "token: ${token}, imm_t: ${imm_t}, i_data: ${i_data}"
                    if [ -z "${r_data}" ]; then
                        reg_t=$(echo  "${token}" | cut -d"${o_data}" -f2)
                        r_data=$(parse_reg "${reg_t}")
                        imm_t=$(echo  "${token}" | cut -d"${o_data}" -f1)
                        i_data=$(parse_imm "${imm_t}")
                    #    echo "i_data: ${i_data}"
                        if [ ! "${o_data}" = "+" ]; then # subtraction
                            echo "ERROR: malformed operand (R#+Imm)"
                            exit 2
                        fi
                    fi

                    if [ ! "${o_data}" = "+" ]; then # subtraction
                        o_data="+"
                    #    echo "./negate ${i_data}"
                        i_data=$(./negate ${i_data})
                    fi

                    x_data="[${r_data}+${i_data}]"

                    if [ -z "${r_data}" ]; then
                        echo "ERROR: malformed operand (no register found)!"
                        exit 2
                    fi

                    if [ -z "${i_data}" ]; then
                        echo "ERROR: malformed operand (no immediate value found)!"
                        exit 2
                    fi
                    let IMM_TALLY=IMM_TALLY+1
                    ;;

                "deref")
                    d_data="${token}"
                    token=$(echo       "${token}" | tr -d '[' | tr -d ']')
                    r_data=$(parse_reg "${token}")
                    i_data=$(parse_imm "${token}")
                    [ ! -z "${r_data}" ] && d_data="[${r_data}]"
                    [ ! -z "${i_data}" ] && d_data="[${i_data}]"
                    [ ! -z "${i_data}" ] && let IMM_TALLY=IMM_TALLY+1
                    ;;

                "register")
                    r_data=$(parse_reg "${token}")
                    ;;

                "immediate")
#                    echo "token: ${token}" 1>&2
                    i_data=$(parse_imm "${token}")
                    [ ! -z "${i_data}" ] && let IMM_TALLY=IMM_TALLY+1
#                    echo "i_data: ${i_data}" 1>&2
                    ;;
            esac

            #echo "[parse_param] attr:   ${attr}"
            echo "${attr}:${r_data}:${i_data}:${d_data}:${x_data}"
            #[ ! -z "${r_data}" ] && echo "[parse_param] r_data: ${r_data} (register)"
            #[ ! -z "${o_data}" ] && echo "[parse_param] o_data: ${o_data} (indexed)"
            #[ ! -z "${i_data}" ] && echo "[parse_param] i_data: ${i_data} (immediate)"
            break
        fi
    done
}

read -e line_input

########################################################################################
##
## polish line_input to ensure consistent presentation
##
line_input=$(echo  "${line_input}" | tr '[:lower:]' '[:upper:]' | tr -s ' ')
line_input=$(echo  "${line_input}" | sed 's/ ,/,/g')  # remove any space before comma
line_input=$(echo  "${line_input}" | sed 's/;.*$//g') # remove comments

echo "line_input:  ${line_input}"

the_opcode=$(echo   "${line_input}" | egrep -o "${OPCODE}")
#num_operands=$(echo "${line_input}" | egrep -o "${TWO_OPER}" | wc -l)

for ((index=0; index<4; index++)); do
    chk=$(echo "${line_input}" | egrep -o "${PTYPE[${index}]}" | wc -l)
    if [ "${chk}" -eq 1 ]; then
        num_operands="${index}"
        break
    fi
done

if [ "${num_operands}" -eq 3 ]; then
    num_operands=2
fi

case "${num_operands}" in
    0)
        echo "${the_opcode}00000000000000000000000000"
        ;;
    
    1)
        #echo "${line_input}" | egrep -o "${ONE_BRANCH[
#declare -a ONE_BRANCH
#declare -a ONE_PARAM
        ;;
    
    2)
        ;;
esac
    


echo "the_opcode:     ${the_opcode}"
echo "num_operands:   ${num_operands}"

found_operands=$(echo "${line_input}" | egrep -o "${OPERAND}" | wc -l)
echo "found_operands: ${found_operands}"

if [ ! "${found_operands}" = "${num_operands}" ]; then
    echo "ERROR: invalid operand for ${the_opcode}"
    exit 1
fi

if [ "${num_operands}" -ge 1 ]; then
    destination=$(echo  "${line_input}" | egrep -o "${OPERAND}"  | head -1)
    #destination=$(echo "${line_input}" | 
    echo
    echo "destination: ${destination}"
    dstresult=$(parse_param "${destination}")

    p_type=$(echo "${dstresult}" | cut -d':' -f1)
    case "${p_type}" in
        "index")
            DSTREG=$(echo "${dstresult}" | cut -d':' -f2)
            DSTIMM=$(echo "${dstresult}" | cut -d':' -f3)
            imm_flag=1
            ;;

        "deref")
            echo "DEREF:  $(echo "${dstresult}" | cut -d':' -f4)"
            DSTREG=$(echo "${dstresult}" | cut  -d':' -f2)
            [ -z "${DSTREG}" ] && DSTIMM=$(echo "${dstresult}" | cut -d':' -f3) && imm_flag=1
            ;;

        "immediate")
            DSTIMM=$(echo "${dstresult}" | cut -d':' -f3)
            imm_flag=1
            ;;

        "register")
            DSTREG=$(echo "${dstresult}"       | cut -d':' -f2)
            ;;
    esac

    ####################################################################################
    ##
    ## For register transactions, also determine its numeric value (DSTVAL)
    ##
    if [ ! -z "${DSTREG}" ]; then
		DSTVAL=$(getregnum "${DSTREG}")
    fi
fi

if [ "${num_operands}" -eq 2 ]; then
    src=$(echo  "${line_input}"         | egrep -o "${OPERAND}"  | head -2 | tail -1)
    echo
    echo "source: ${src}"
    srcresult=$(parse_param "${src}")
    p_type=$(echo "${srcresult}" | cut -d':' -f1)
    case "${p_type}" in
        "index")
            SRCREG=$(echo "${srcresult}" | cut -d':' -f2)
            SRCIMM=$(echo "${srcresult}" | cut -d':' -f3)
            imm_flag=1
            ;;

        "deref")
            echo "DEREF:  $(echo "${srcresult}" | cut -d':' -f4)"
            SRCREG=$(echo "${srcresult}" | cut  -d':' -f2)
            [ -z "${SRCREG}" ] && SRCIMM=$(echo "${srcresult}" | cut -d':' -f3) && imm_flag=1
            ;;

        "immediate")
            SRCIMM=$(echo "${srcresult}" | cut -d':' -f3)
            imm_flag=1
            ;;

        "register")
            SRCREG=$(echo "${srcresult}"       | cut -d':' -f2)
            ;;
    esac

    ####################################################################################
    ##
    ## For register transactions, also determine its numeric value (SRCVAL)
    ##
    if [ ! -z "${SRCREG}" ]; then
		SRCVAL=$(getregnum "${SRCREG}")
    fi
fi

echo "IMM_TALLY: ${IMM_TALLY}"
if [ "${IMM_TALLY}" -gt 1 ]; then
    echo "ERROR: Exceeded maximum threshold for immediate values!"
    exit 3
fi

if [ "${the_opcode}" = "MOV" ]; then
    for ((index=0; index<8; index++)); do
        the_operands=$(echo "${line_input}" | cut -d' ' -f2-)
        match=$(echo "${the_operands}" | egrep -qio "${MOV_PARAM[${index}]}" && echo "true" || echo "false")
        if [ "${match}" = "true" ]; then
            ADDRMODE=$(echo "obase=2; ${index}" | bc -q)
            ADDRMODE=$(printf "%.3d" "${ADDRMODE}")
            break
        fi
    done
else
    ADDRMODE="000"
fi

PORT="00000000000000"

echo "----"
echo "opcode:    \"${the_opcode}\" (0x${opcode[${the_opcode}]})"
echo "imm_flag:  ${imm_flag}"
IMMEDIATE=
[ ! -z "${DSTREG}"    ] && echo "dstreg:    ${DSTREG}" || IMMEDIATE="${DSTIMM}"
[   -z "${DSTREG}"    ] && DSTVAL="0000"
[ ! -z "${SRCREG}"    ] && echo "srcreg:    ${SRCREG}" || IMMEDIATE="${SRCIMM}"
[   -z "${SRCREG}"    ] && SRCVAL="0000"
[ ! -z "${IMMEDIATE}" ] && echo "immediate: ${IMMEDIATE}"
[ ! -z "${DSTIMM}"    ] && IMMEDIATE="${DSTIMM}"
[ ! -z "${SRCIMM}"    ] && IMMEDIATE="${SRCIMM}"

echo "DSTVAL:    ${DSTVAL}"
echo "DSTIMM:    ${DSTIMM}"
echo "SRCVAL:    ${SRCVAL}"
echo "SRCIMM:    ${SRCIMM}"
echo "ADDRMODE:  ${ADDRMODE}"
echo "----"
echo "instruction: ${opcode[${the_opcode}]} ${imm_flag} ${DSTVAL} ${SRCVAL} ${ADDRMODE} ${PORT}"
binary="${opcode[${the_opcode}]}${imm_flag}${DSTVAL}${SRCVAL}${ADDRMODE}${PORT}"
instruction=$(echo "obase=10; ibase=2; ${binary}" | bc -q)
instruction=$(printf "0x%.8X" "${instruction}")
echo "instruction: ${instruction}"
if [ ! -z "${IMMEDIATE}" ]; then
    echo "immediate:   ${IMMEDIATE}"
fi

echo "done"

exit 0
