#!/usr/bin/env bash
### 
###             v32as - Vircon32 assembler written in BASH, powered by
###                     Regular Expressions
### 
###              usage: v32as [OPTION..] [ASMFILE..]
### 
###            option - description
### =================   ===================================================
###              bios   assemble for BIOS
###              cart   assemble for CART
###              none   standalone instruction assembly (default)
###              step   pause after each instruction
###            binary   output resulting binary machine code to STDOUT
###           verbose   increase verbosity
###              help   display usage information and exit
### 
### NOTE: It is meant for v32pp, the Vircon32 Assembly Pre-Processor, to be
### run prior to passing the code through this assembler. Furthermore,  for
### the production of an actual VBIN file, a further tool is required. This
### assembler will ONLY convert to machine code, and nothing more.
### 
########################################################################################

########################################################################################
##
## Process command-line arguments
##
DO_HELP=$(echo "${*}" | egrep -qio '\<help\>' && echo "true" || echo "false")
VERBOSE=$(echo "${*}" | egrep -qio '\<verbos' && echo "true" || echo "false")
DO_BIOS=$(echo "${*}" | egrep -qio '\<bios\>' && echo "true" || echo "false")
DO_CART=$(echo "${*}" | egrep -qio '\<cart\>' && echo "true" || echo "false")
BINARY=$(echo  "${*}" | egrep -qio '\<binary' && echo "true" || echo "false")
DO_STEP=$(echo "${*}" | egrep -qio '\<step\>' && echo "true" || echo "false")
REGEX='\<(bios|cart|none|binary|step|verbose|help)\>'
ARGS=$(echo    "${*}"    | tr ' ' '\n' | egrep -v "${REGEX}" | tr '\n' ' ')
ARGS=$(echo    "${ARGS}" | grep -v '^[ ]*$')

########################################################################################
##
## Display usage information if requested (and exit)
##
[ "${DO_HELP}" = "true" ] && cat ${0} | grep '^### ' | tr -d '#' && exit 0

########################################################################################
##
## Declare and initialize variables
##
BINCODE=$(whereis -b bincode | cut -d' ' -f2)
FLOATIFY="${BINCODE} -t -f "
NEGATE="${BINCODE} -t -n -w "
TMP=$(mktemp -p /tmp v32as.XXXX)
BINFILE="${TMP}.bin"
LABELSYM="${TMP}.SYM"

########################################################################################
##
## Establish RegEx patterns for tokens
##
OPCODE='^(IN|JT|JF|OR|[A-Z][A-Z2]{2,4})$'
REGISTER='(R[0-9]|R1[0-5]|BP|SP|CR|SR|DR)'
HEX1='0[Xx][0-9A-F]{1,8}'
HEX2='[0-9A-F]{1,8}[Hh]'
OCT='0[0-7]+'
BIN='0[Bb][01]{1,32}'
DEC1='[+-]?([0-9]|[1-9][0-9]*)'
DEC2='#[+-]?([0-9]|[1-9][0-9]*)'
FLOAT='[+-]?([0-9]\.[0-9][0-9]*|[1-9][0-9]*\.[0-9][0-9]*)'
IMMEDIATE="(${BIN}|${OCT}|${DEC1}|${DEC2}|${FLOAT}|${HEX1}|${HEX2})"
INDEX="[-+]"
INDEXED="${REGISTER}[-+]${IMMEDIATE}"
DEREF='[[].*[]]'
IOPORTSYM='(TIM|RNG|GPU|SPU|INP|CAR|MEM)_[A-Z][A-Za-z]*'
IOPORTHEX='0[Xx][0-6][01][0-9A-F]'
GPUCMDSYM='GPU(Command|BlendingMode)_[A-Z][A-Za-z]*'
SNDCMDSYM='SPU(Command|ChannelState)_[A-Z][A-Za-z]*'
IOPORTCMDHEX='0[Xx][1-4][0-5]'
IOPORT="${IOPORTSYM}|${IOPORTHEX}"
LABEL='_[_A-Za-z0-9][_A-Za-z0-9]*'
OPERAND="(${DEREF}|${REGISTER}|${IMMEDIATE}|${IOPORT}|${LABEL})"

declare -A ITYPE
ITYPE["hex1"]="^${HEX1}$"
ITYPE["hex2"]="^${HEX2}$"
ITYPE["oct"]="^${OCT}$"
ITYPE["bin"]="^${BIN}$"
ITYPE["dec"]="^${DEC1}$"
ITYPE["dec2"]="^${DEC2}$"
ITYPE["float"]="^${FLOAT}$"

########################################################################################
##
## opcode array, providing the binary opcode values
##
declare -A opcode
opcode["HLT"]="000000"
opcode["WAIT"]="000001"
opcode["JMP"]="000010"
opcode["CALL"]="000011"
opcode["RET"]="000100"
opcode["JT"]="000101"
opcode["JF"]="000110"
opcode["IEQ"]="000111"
opcode["INE"]="001000"
opcode["IGT"]="001001"
opcode["IGE"]="001010"
opcode["ILT"]="001011"
opcode["ILE"]="001100"
opcode["FEQ"]="001101"
opcode["FNE"]="001110"
opcode["FGT"]="001111"
opcode["FGE"]="010000"
opcode["FLT"]="010001"
opcode["FLE"]="010010"
opcode["MOV"]="010011"
opcode["LEA"]="010100"
opcode["PUSH"]="010101"
opcode["POP"]="010110"
opcode["IN"]="010111"
opcode["OUT"]="011000"
opcode["MOVS"]="011001"
opcode["SETS"]="011010"
opcode["CMPS"]="011011"
opcode["CIF"]="011100"
opcode["CFI"]="011101"
opcode["CIB"]="011110"
opcode["CFB"]="011111"
opcode["NOT"]="100000"
opcode["AND"]="100001"
opcode["OR"]="100010"
opcode["XOR"]="100011"
opcode["BNOT"]="100100"
opcode["SHL"]="100101"
opcode["IADD"]="100110"
opcode["ISUB"]="100111"
opcode["IMUL"]="101000"
opcode["IDIV"]="101001"
opcode["IMOD"]="101010"
opcode["ISGN"]="101011"
opcode["IMIN"]="101100"
opcode["IMAX"]="101101"
opcode["IABS"]="101110"
opcode["FADD"]="101111"
opcode["FSUB"]="110000"
opcode["FMUL"]="110001"
opcode["FDIV"]="110010"
opcode["FMOD"]="110011"
opcode["FSGN"]="110100"
opcode["FMIN"]="110101"
opcode["FMAX"]="110110"
opcode["FABS"]="110111"
opcode["FLR"]="111000"
opcode["CEIL"]="111001"
opcode["ROUND"]="111010"
opcode["SIN"]="111011"
opcode["ACOS"]="111100"
opcode["ATAN2"]="111101"
opcode["LOG"]="111110"
opcode["POW"]="111111"

declare -A IOPORT
IOPORT["TIM_CurrentDate"]="0x000"
IOPORT["TIM_CurrentTime"]="0x001"
IOPORT["TIM_FrameCounter"]="0x002"
IOPORT["TIM_CycleCounter"]="0x003"
IOPORT["RNG_CurrentValue"]="0x100"
IOPORT["GPU_Command"]="0x200"
IOPORT["GPU_RemainingPixels"]="0x201"
IOPORT["GPU_ClearColor"]="0x202"
IOPORT["GPU_MultiplyColor"]="0x203"
IOPORT["GPU_ActiveBlending"]="0x204"
IOPORT["GPU_SelectedTexture"]="0x205"
IOPORT["GPU_SelectedRegion"]="0x206"
IOPORT["GPU_DrawingPointX"]="0x207"
IOPORT["GPU_DrawingPointY"]="0x208"
IOPORT["GPU_DrawingScaleX"]="0x209"
IOPORT["GPU_DrawingScaleY"]="0x20A"
IOPORT["GPU_DrawingAngle"]="0x20B"
IOPORT["GPU_RegionMinX"]="0x20C"
IOPORT["GPU_RegionMinY"]="0x20D"
IOPORT["GPU_RegionMaxX"]="0x20E"
IOPORT["GPU_RegionMaxY"]="0x20F"
IOPORT["GPU_RegionHotspotX"]="0x210"
IOPORT["GPU_RegionHotspotY"]="0x211"
IOPORT["SPU_Command"]="0x300"
IOPORT["SPU_GlobalVolume"]="0x301"
IOPORT["SPU_SelectedSound"]="0x302"
IOPORT["SPU_SelectedChannel"]="0x303"
IOPORT["SPU_SoundLength"]="0x304"
IOPORT["SPU_SoundPlayWithLoop"]="0x305"
IOPORT["SPU_SoundLoopStart"]="0x306"
IOPORT["SPU_SoundLoopEnd"]="0x307"
IOPORT["SPU_ChannelState"]="0x308"
IOPORT["SPU_ChannelAssignedSound"]="0x309"
IOPORT["SPU_ChannelVolume"]="0x30A"
IOPORT["SPU_ChannelSpeed"]="0x30B"
IOPORT["SPU_ChannelLoopEnabled"]="0x30C"
IOPORT["SPU_ChannelPosition"]="0x30D"
IOPORT["INP_SelectedGamepad"]="0x400"
IOPORT["INP_GamepadConnected"]="0x401"
IOPORT["INP_GamepadLeft"]="0x402"
IOPORT["INP_GamepadRight"]="0x403"
IOPORT["INP_GamepadUp"]="0x404"
IOPORT["INP_GamepadDown"]="0x405"
IOPORT["INP_GamepadButtonStart"]="0x406"
IOPORT["INP_GamepadButtonA"]="0x407"
IOPORT["INP_GamepadButtonB"]="0x408"
IOPORT["INP_GamepadButtonX"]="0x409"
IOPORT["INP_GamepadButtonY"]="0x40A"
IOPORT["INP_GamepadButtonL"]="0x40B"
IOPORT["INP_GamepadButtonR"]="0x40C"
IOPORT["CAR_Connected"]="0x500"
IOPORT["CAR_ProgramROMSize"]="0x501"
IOPORT["CAR_NumberOfTextures"]="0x502"
IOPORT["CAR_NumberOfSounds"]="0x503"
IOPORT["MEM_Connected"]="0x600"

declare -A IOPORTCMD
IOPORTCMD["GPUCommand_ClearScreen"]="0x10"
IOPORTCMD["GPUCommand_DrawRegion"]="0x11"
IOPORTCMD["GPUCommand_DrawRegionZoomed"]="0x12"
IOPORTCMD["GPUCommand_DrawRegionRotated"]="0x13"
IOPORTCMD["GPUCommand_DrawRegionRotozoomed"]="0x14"
IOPORTCMD["GPUBlendingMode_Alpha"]="0x20"
IOPORTCMD["GPUBlendingMode_Add"]="0x21"
IOPORTCMD["GPUBlendingMode_Subtract"]="0x22"
IOPORTCMD["SPUCommand_PlaySelectedChannel"]="0x30"
IOPORTCMD["SPUCommand_PauseSelectedChannel"]="0x31"
IOPORTCMD["SPUCommand_StopSelectedChannel"]="0x32"
IOPORTCMD["SPUCommand_PauseAllChannels"]="0x33"
IOPORTCMD["SPUCommand_ResumeAllChannels"]="0x34"
IOPORTCMD["SPUCommand_StopAllChannels"]="0x35"
IOPORTCMD["SPUChannelState_Stopped"]="0x40"
IOPORTCMD["SPUChannelState_Paused"]="0x41"
IOPORTCMD["SPUChannelState_Playing"]="0x42"

imm_flag=0

########################################################################################
##
## getregnum(): obtain numeric value of register
##
function getregnum()
{
    REG="${1}"
    VAL=
    case "${REG}" in
        "CR")
            VAL="1011"
            ;;
        "SR")
            VAL="1100"
            ;;
        "DR")
            VAL="1101"
            ;;
        "BP")
            VAL="1110"
            ;;
        "SP")
            VAL="1111"
            ;;
        "IP")
            VAL="none"
            ;;
        "IR")
            VAL="none"
            ;;
        "IV")
            VAL="none"
            ;;
        *)
            VAL=$(echo "${REG}" | tr -d 'A-Za-z:')
            VAL=$(echo "obase=2; ${VAL}" | bc -q)
            VAL=$(printf "%.4d" "${VAL}")
            ;;
    esac
    echo "${VAL}"
}

########################################################################################
##
## getportnum(): obtain numeric value of IOPort
##
function getportnum()
{
    portname="${1}"

    IOP="${IOPORT[${portname}]}"

    echo "${IOP}"
}

########################################################################################
##
## getportcmdnum(): obtain numeric value of IOPort Command
##
function getportcmdnum()
{
    cmdname="${1}"

    CMD="${IOPORTCMD[${cmdname}]}"

    echo "${CMD}"
}

########################################################################################
##
## parse_reg(): function to parse and return the register component from  the
##              provided token. Will ensure the returned value is using upper
##              case letters. Supports all the aliased registers.
##
function parse_reg()
{
    token="${1}"
    the_reg=$(echo "${token}" | egrep -o "^${REGISTER}$")
    the_reg="${the_reg^^}"
    echo "${the_reg}"
}

########################################################################################
##
## parse_imm(): function to parse and convert immediate value to standard hex
##              representation, leading '0x', and 8 total digits. It converts
##              a number of recognized formats:
##
##              0bXXXX - binary value (1-32 bits)
##              0XXXX  - octal value
##              XXXX   - decimal value
##              #XXXX  - decimal value
##              0xXXXX - standard hexadecimal representation (the target)
##              XXXXH  - alternate hexadecimal representation
##              X.XXXX - floating point value
##
function parse_imm()
{
    ####################################################################################
    ##
    ## declare and initialize variables
    ##
    token="${1}"
    label="${2}"
    d_imm=
    t_imm=
    l_imm=

    ####################################################################################
    ##
    ## check each potential category to validate data as immediate
    ##
    for attr in bin oct dec1 dec2 hex1 hex2 float ${label}; do

        case "${attr}" in
            "bin")
                d_imm=$(echo "${token}" | egrep -o "^${BIN}$")
                d_imm="${d_imm//0[bB]/}"
                t_imm=$(echo "${token}" | egrep -o "^${BIN}$" | wc -l)
                d_imm=$(echo "obase=16; ibase=2; ${d_imm}"  | bc)
                ;;

            "oct")
                d_imm=$(echo "${token}" | egrep -o "^${OCT}$")
                t_imm=$(echo "${token}" | egrep -o "^${OCT}$" | wc -l)
                d_imm=$(echo "obase=16; ibase=8; ${d_imm}"  | bc)
                ;;

            "dec1")
                d_imm=$(echo "${token}" | egrep -o "^${DEC1}$")
                d_imm="${d_imm//+/}"
                d_chk=$(echo "${d_imm}" | egrep -qio '^-' && echo "true")
                if [ ! -z "${d_chk}" ]; then
                    d_imm=$(echo "${token}")
                    d_imm="${d_imm//-/}"
                    d_imm=$(echo "obase=2; (2^32)-${d_imm}"  | bc)
                    d_imm=$(echo "ibase=2; ${d_imm}"         | bc)
                fi
                t_imm=$(echo "${token}" | egrep -o "^${DEC1}$" | wc -l)
                d_imm=$(echo "obase=16; ibase=10; ${d_imm}"  | bc)
                ;;

            "dec2")
                d_imm=$(echo "${token}" | egrep -o "^${DEC2}$")
                d_imm="${d_imm//[#+]/}"
                d_chk=$(echo "${d_imm}" | egrep -qio '^-' && echo "true")
                if [ ! -z "${d_chk}" ]; then
                    d_imm=$(echo "${d_imm}")
                    d_imm="${d_imm//-/}"
                    d_imm=$(echo "obase=2; (2^32)-${d_imm}"    | bc)
                    d_imm=$(echo "ibase=2; ${d_imm}"           | bc)
                fi
                t_imm=$(echo "${token}" | egrep -o "^${DEC2}$" | wc -l)
                d_imm=$(echo "obase=16; ibase=10; ${d_imm}"    | bc)
                ;;

            "hex1")
                d_imm=$(echo "${token}" | egrep -o "^${HEX1}$")
                d_imm="${d_imm//0[Xx]/}"
                t_imm=$(echo "${token}" | egrep -o "^${HEX1}$" | wc -l)
                ;;

            "hex2")
                d_imm=$(echo "${token}" | egrep -o "^${HEX2}$")
                d_imm="${d_imm//[Hh]/}"
                t_imm=$(echo "${token}" | egrep -o "^${HEX2}$" | wc -l)
                ;;

            "float")
                d_imm=$(echo "${token}" | egrep -o "^${FLOAT}$")
                t_imm=$(echo "${token}" | egrep -o "^${FLOAT}$" | wc -l)
                if [ "${t_imm}" -gt 0 ]; then
                    d_imm=$(${FLOATIFY} "${token}")
                    d_imm="${d_imm//0x/}"
                fi
                ;;

            "label")
                d_imm=$(echo "${token}" | egrep -o "^${LABEL}$")
                t_imm=$(echo "${token}" | egrep -o "^${LABEL}$" | wc -l)

                ########################################################################
                ##
                ## if alabel, check if there is already an entry within LABELSYM;
                ## if not, append it
                ##
                if [ ! -z "${d_imm}" ]; then
                    l_imm="true"
                    lchk=$(cat ${LABELSYM} | egrep -o "^${d_imm}:" | wc -l)
                    if [ "${lchk}" -eq 1 ]; then
                        laddr=$(cat ${LABELSYM} | egrep "^${d_imm}:" | cut -d':' -f2)
                        d_imm="${laddr}"
                    fi
                fi
                ;;
        esac

        [ "${t_imm}" -gt 0 ] && break
    done

    ####################################################################################
    ##
    ## if resulting immediate data (d_imm) is a number, it will be in hex,
    ## so ensure it is formatted properly. But do not do so if a label.
    ##
    if [ ! -z "${d_imm}" ] && [ -z "${l_imm}" ]; then
        d_imm="0x${d_imm}"
        d_imm=$(printf "0x%.8X" "${d_imm}")
    fi
    echo "${d_imm}"
}

function parse_operator()
{
    token="${1}"
    for attr in bin oct dec1 dec2 hex1 hex2; do
        p_data=$(echo "${token}"  | egrep -o "${ITYPE[${attr}]}")
        p_type=$(echo "${token}"  | egrep -o "${ITYPE[${attr}]}" | wc -l)
        if [ "${p_type}" -eq 1 ]; then
            case "${attr}" in
                "+")
                    ;;
                "-")
                    ;;
            esac
            p_data=$(echo "${p_data}"   | tr    'X' 'x' | cut -d'x' -f2)
            p_data=$(printf "0x%8s" "${p_data}" | tr ' ' '0')
            break
        fi
    done
    echo "${p_data}"
}

########################################################################################
##
## parse_iop(): function to parse and return the hex address of the  provided
##              V32 IOPort
##
function parse_iop()
{
    portname="${1}"
    portnum=
    portchk=$(echo "${portname}" | egrep -o "^${IOPORTSYM}$")
    numchk=

    [ ! -z "${portchk}" ] && portnum="${IOPORT[${portname}]}"
    [   -z "${portchk}" ] && numchk=$(echo "${portname}" | egrep -o "^${IOPORTHEX}$")
    [ ! -z "${numchk}"  ] && portnum="${portname}"
    #[   -z "${portnum}" ] && portnum="${IOPORTCMD[${portname}]}"
    #[   -z "${portnum}" ] && portnum=$(echo "${portname}" | egrep -o "${IOPORTCMDHEX}$")

    debug "portname:  ${portname}" 1>&2
    debug "portnum:   ${portnum}"  1>&2

    echo "${portnum}"
}

########################################################################################
##
## parse_param(): general operand processing; figure out what it is and obtain
##                useful, pertinent data that is returned
##
function parse_param()
{
    operand="${1}"
    categories="${2}"
    flags="${3}"
    deref=$(echo "${flags}" | egrep -qio '\<deref\>' && echo "true")
    label=$(echo "${flags}" | egrep -io  '\<label\>')
    pFLG=0
    pREF=

   # debug    "operand:    ${operand}"    1>&2
   # debug    "categories: ${categories}" 1>&2
   # debug    "flags:      ${flags}"      1>&2

    ####################################################################################
    ##
    ## check for a dereferenced parameter, mark it and then update the
    ## parameter string for further processing
    ##
    if [ ! -z "${deref}" ] && [ "${deref}" = "true" ]; then
        chk=$(echo "${operand}" | egrep -o "^${DEREF}$"   | wc -l)
        if [ "${chk}" -eq 1 ]; then
            pREF="true"
            operand=$(echo "${operand}" | tr -d '[' | tr -d ']')
        fi
    fi

    ####################################################################################
    ##
    ## process for each indicated category, based on the potential set
    ## of scenarios per given instruction
    ##
    for item in ${categories}; do

        case ${item} in

            ############################################################################
            ##
            ## check for immediate parameter
            ##
            "immediate")
                pIMM=$(parse_imm "${operand}" ${label})
                [ ! -z "${pIMM}" ] && pFLG=1 && break
                ;;

            ############################################################################
            ##
            ## check for register parameter
            ##
            "register")
                pREG=$(parse_reg "${operand}")
                [ ! -z "${pREG}" ] && break
                ;;

            ############################################################################
            ##
            ## check for an indexed parameter, split it and identify each of
            ## the components
            ##
            "indexed")
                [ -z "${pREF}"  ] && do_error ${offset} ${line_input} "invalid indexing use"
                chk=$(echo       "${operand}" | egrep -o "^${INDEXED}$" | wc -l)
                if [ "${chk}" -eq 1 ]; then
                    delim=$(echo "${operand}" | grep -o '[+]')
                    [ -z "${delim}" ] && delim=$(echo "${operand}" | grep -o '[-]')
                    left=$(echo  "${operand}" | cut -d"${delim}" -f1)
                    right=$(echo "${operand}" | cut -d"${delim}" -f2)
                    pREG=$(parse_reg "${left}")
                    pIMM=$(parse_imm "${right}")
                    pFLG=1
                    [ "${delim}" = "-" ] && pIMM=$(${NEGATE} ${pIMM})
                    break
                fi
                ;;

            ############################################################################
            ##
            ## check for IOPort parameter (symbolic or hex numeric)
            ##
            "ioport")
                pIOP=$(parse_iop "${operand}")
                ;;
        esac
    done

    ################################################################################
    ##
    ## For register transactions, also determine its numeric value (SRCVAL)
    ##
    if [ ! -z "${pREG}" ]; then
        pVAL=$(getregnum "${pREG}")
    fi

    ################################################################################
    ##
    ## Display the results
    ##
    echo     "${pREG}:${pVAL}:${pIMM}:${pREF}:${pFLG}:${pIOP}:${label}"
}

function do_error()
{
    offset="${1}"
    offset=$(echo "${offset}" | egrep -io "^${HEX1}$")
    [ ! -z "${offset}" ] && shift 1

    opcode=$(echo      "${1}" | cut -d' ' -f1)
    dst_operand=$(echo "${1}" | cut -d' ' -f2)
    src_operand=$(echo "${1}" | cut -d' ' -f3)
    error_type="${2}"

    [   -z "${error_type}" ] && error_type="invalid use"

    [   -z "${offset}" ] && echo -n "[ERROR] "
    [ ! -z "${offset}" ] && echo -n "[ERROR@${offset}] "

    if [   ! -z "${src_operand}" ]; then
        echo "${error_type} on \"${opcode} ${dst_operand}, ${src_operand}\""
    elif [ ! -z "${dst_operand}" ]; then
        echo "${error_type} on \"${opcode} ${dst_operand}\""
    else
        echo "${error_type} on \"${opcode}\""
    fi
    
    exit 1
}

########################################################################################
##
## debug function (displays information to STDERR, when enabled)
##
function debug()
{
    ####################################################################################
    ##
    ## if verbosity is not enabled, bail out
    ##
    [ "${VERBOSE}" = "false" ] && return

    ####################################################################################
    ##
    ## declare and initialize variables
    ##
    NONEWLINE=
    NO_HEADER=

    ####################################################################################
    ##
    ## grab the location from the BASH function call array
    ##
    place="${FUNCNAME[1]}"
    [ "${place}" = "main" ] && place=$(basename ${0})

    ####################################################################################
    ##
    ## allow for turning off auto-newline
    ##
    [ "${1}" = "-n"       ] && NONEWLINE="true" && shift 1

    ####################################################################################
    ##
    ## allow for turning off auto-newline
    ##
    [ "${1}" = "-H"       ] && NO_HEADER="true" && shift 1

    ####################################################################################
    ##
    ## the content to actually be displayed
    ##
    message="${1}"

    ####################################################################################
    ##
    ## display the header, if enabled
    ##
    [   -z "${NO_HEADER}" ] && echo -n "[${place}] " 1>&2

    ####################################################################################
    ##
    ## deliver the message, based on settings
    ##
    [ ! -z "${NONEWLINE}" ] && echo -n "${message}"  1>&2
    [   -z "${NONEWLINE}" ] && echo    "${message}"  1>&2
}

########################################################################################
##
## start of assembler logic
##
[ "${DO_BIOS}" = "true" ] && offset=0x10000000
[ "${DO_BIOS}" = "true" ] && debug -H "[v32as] assembling for BIOS"
[ "${DO_CART}" = "true" ] && offset=0x20000000
[ "${DO_CART}" = "true" ] && debug -H "[v32as] assembling for CART"

########################################################################################
##
## Check for STDIN redirection, 
##
if [   -z "${ARGS}" ]; then

    ####################################################################################
    ##
    ## polish input on its way to the input file
    ##
    cat | tr -s ' ' | sed 's/ ,/,/g' | sed 's/;.*$//g'                  >  ${TMP}
    DATAFILE="${TMP}"
else
    DATAFILE="${ARGS}"
fi

########################################################################################
##
## ensure TMP exists
##
echo -n                                                                 >  ${TMP}

########################################################################################
##
## ensure LABELSYM exists
##
echo -n                                                                 >  ${LABELSYM}

########################################################################################
##
## process for each input file
##
for file in ${DATAFILE}; do

    ####################################################################################
    ##
    ## obtain input
    ##
    for line in $(cat ${file} | tr ' ' '@'); do

        ################################################################################
        ##
        ## reset variables
        ##
        the_opcode=
        imm_flag=0
        dst_operand=
        DSTREG=
        DSTVAL=
        DSTIMM=
        DSTFLG=0
        src_operand=
        SRCREG=
        SRCVAL=
        SRCIMM=
        SRCFLG=0
        ADDR=
        PORT=
        instruction=
        IMMEDIATE=
        LABELFLAG="false"

        line_input=$(echo "${line}" | tr '@' ' ')
        line_input=$(echo  "${line_input}" | tr -s ' ')       # excessive spaces
        line_input=$(echo  "${line_input}" | sed 's/ ,/,/g')  # space before comma
        line_input=$(echo  "${line_input}" | sed 's/;.*$//g') # comments

        debug    "line_input:    ${line_input}"

        num_operands=0
        for token in `echo "${line_input}" | tr -d ','`; do

            if [ "${num_operands}" -eq 0 ]; then
                label_check=$(echo "${token}" | egrep -io "^${LABEL}:$")
                if [ -z "${label_check}" ]; then
                    the_opcode=$(echo  "${token}" | egrep -io "${OPCODE}")
                    the_opcode="${the_opcode^^}"
                    if [ -z "${opcode[${the_opcode}]}" ]; then
                        do_error ${offset} \
                                 "${the_opcode} ${dst_operand} ${src_operand}" \
                                 "invalid instruction"
                    fi
                else
                    debug    "LABEL definition \"${token}\" at ${offset}"
                    lchk=$(cat ${LABELSYM} | egrep -o "^${token}"  | wc -l)
                    [ "${lchk}" -eq 0 ] && echo "${token}${offset}"    >> ${LABELSYM}
                    if [ "${lchk}" -gt 0 ]; then
                        do_error ${offset} " " "duplicate label ${token}"
                    fi
                    LABELFLAG="true"
                    break
                fi
            elif [ "${num_operands}" -eq 1 ]; then
                dst_operand=$(echo "${token}" | egrep -io "${OPERAND}")
            else
                src_operand=$(echo "${token}" | egrep -io "${OPERAND}")
            fi

            let num_operands=num_operands+1
        done
        let num_operands=num_operands-1

        ############################################################################
        ##
        ## if we are dealing with a label definition, avoid further instruction
        ## processing
        ##
        if [ "${LABELFLAG}" = "true" ]; then
            continue
        fi
 
        case "${the_opcode}" in
            "IN")
                dst_types="register"
                dst_flags=
                src_types="ioport"
                src_flags=
                ;;

            "OUT")
                dst_types="ioport"
                dst_flags=
                src_types="immediate register"
                src_flags=
                ;;

            "JMP"|"CALL")
                dst_types="immediate register"
                dst_flags="label"
                src_types=
                src_flags=
                ;;

            "JT"|"JF")
                dst_types="immediate register"
                dst_flags="label"
                src_types="register"
                src_flags=
                ;;

            "PUSH"|"POP"|"CMPS"|"CIF"|"CFI"|"CIB"|"CFB"|"NOT"|"BNOT"|"ISGN"|"IABS")
                dst_types="register"
                dst_flags=
                src_types=
                src_flags=
                ;;
            
            "FSGN"|"FABS"|"FLR"|"CEIL"|"ROUND"|"SIN"|"ACOS"|"LOG")
                dst_types="register"
                dst_flags=
                src_types=
                src_flags=
                ;;

            "HLT"|"WAIT"|"RET"|"MOVS"|"SETS")
                dst_types=
                dst_flags=
                src_types=
                src_flags=
                ;;

            "LEA")
                dst_types="register"
                dst_flags=
                src_types="register indexed"
                src_flags="deref"
                ;;
            
            "MOV")
                dst_types="immediate register indexed"
                dst_flags="deref"
                src_types="immediate register indexed"
                src_flags="deref"
                ;;
            
            *)
                dst_types="register"
                dst_flags=
                src_types="immediate register"
                src_flags=
                ;;
        esac

        ############################################################################
        ##
        ## If available, process the destination operand
        ##
        if [ ! -z "${dst_types}" ]; then
            result=$(parse_param ${dst_operand} "${dst_types}" "${dst_flags}")
            if [ "${result}" = "::::0::" ]; then
                do_error ${offset} "${the_opcode} ${dst_operand} ${src_operand}" syntax
            fi
            DSTREG=$(echo "${result}" | cut -d':' -f1)
            DSTVAL=$(echo "${result}" | cut -d':' -f2)
            DSTIMM=$(echo "${result}" | cut -d':' -f3)
            DSTREF=$(echo "${result}" | cut -d':' -f4)
            DSTFLG=$(echo "${result}" | cut -d':' -f5)
            DSTPRT=$(echo "${result}" | cut -d':' -f6)
            DSTLBL=$(echo "${result}" | cut -d':' -f7)
        fi

        ################################################################################
        ##
        ## If available, process the source operand
        ##
        if [ ! -z "${src_types}" ]; then
            result=$(parse_param ${src_operand} "${src_types}" "${src_flags}")
            if [ "${result}" = "::::0:" ]; then
                do_error ${offset} "${the_opcode} ${dst_operand} ${src_operand}" syntax
            fi
            SRCREG=$(echo "${result}" | cut -d':' -f1)
            SRCVAL=$(echo "${result}" | cut -d':' -f2)
            SRCIMM=$(echo "${result}" | cut -d':' -f3)
            SRCREF=$(echo "${result}" | cut -d':' -f4)
            SRCFLG=$(echo "${result}" | cut -d':' -f5)
            SRCPRT=$(echo "${result}" | cut -d':' -f6)
            SRCLBL=$(echo "${result}" | cut -d':' -f7)
        fi

        ################################################################################
        ##
        ## Error check: at most, only one immediate flag can be set across both the
        ## parameters
        ##
        if [ "${DSTFLG}" -eq 1 ] && \
           [ "${SRCFLG}" -eq 1 ]; then
            do_error ${offset} "${the_opcode} ${dst_operand} ${src_operand}" syntax
            #echo "ERROR: illegal multiple immediate operands"
        fi

        ################################################################################
        ##
        ## Set imm_flag if set on either parameter
        ##
        [ ! -z "${DSTFLG}" ] && [ "${DSTFLG}" -eq 1 ] && imm_flag="${DSTFLG}"
        [ ! -z "${SRCFLG}" ] && [ "${SRCFLG}" -eq 1 ] && imm_flag="${SRCFLG}"

        ################################################################################
        ##
        ## If MOV, determine addressing mode (ADDR)
        ##
        if [ "${the_opcode}" = "MOV" ]; then
            for ((index=0; index<8; index++)); do
                case ${index} in
                    0) # REG, IMM
                        [ ! -z "${DSTREG}" ] && [   -z "${SRCREG}" ] && \
                        [   -z "${DSTIMM}" ] && [ ! -z "${SRCIMM}" ] && \
                        [   -z "${DSTREF}" ] && [   -z "${SRCREF}" ] && ADDR="${index}"
                        ;;

                    1) # REG, REG
                        [ ! -z "${DSTREG}" ] && [ ! -z "${SRCREG}" ] && \
                        [   -z "${DSTIMM}" ] && [   -z "${SRCIMM}" ] && \
                        [   -z "${DSTREF}" ] && [   -z "${SRCREF}" ] && ADDR="${index}"
                        ;;

                    2) # REG, [IMM]
                        [ ! -z "${DSTREG}" ] && [   -z "${SRCREG}" ] && \
                        [   -z "${DSTIMM}" ] && [ ! -z "${SRCIMM}" ] && \
                        [   -z "${DSTREF}" ] && [ ! -z "${SRCREF}" ] && ADDR="${index}"
                        ;;

                    3) # REG, [REG]
                        [ ! -z "${DSTREG}" ] && [ ! -z "${SRCREG}" ] && \
                        [   -z "${DSTIMM}" ] && [   -z "${SRCIMM}" ] && \
                        [   -z "${DSTREF}" ] && [ ! -z "${SRCREF}" ] && ADDR="${index}"
                        ;;

                    4) # REG, [REG+IMM]
                        [ ! -z "${DSTREG}" ] && [ ! -z "${SRCREG}" ] && \
                        [   -z "${DSTIMM}" ] && [ ! -z "${SRCIMM}" ] && \
                        [   -z "${DSTREF}" ] && [ ! -z "${SRCREF}" ] && ADDR="${index}"
                        ;;

                    5) # [IMM], REG
                        [   -z "${DSTREG}" ] && [ ! -z "${SRCREG}" ] && \
                        [ ! -z "${DSTIMM}" ] && [   -z "${SRCIMM}" ] && \
                        [ ! -z "${DSTREF}" ] && [   -z "${SRCREF}" ] && ADDR="${index}"
                        ;;

                    6) # [REG], REG
                        [ ! -z "${DSTREG}" ] && [ ! -z "${SRCREG}" ] && \
                        [   -z "${DSTIMM}" ] && [   -z "${SRCIMM}" ] && \
                        [ ! -z "${DSTREF}" ] && [   -z "${SRCREF}" ] && ADDR="${index}"
                        ;;

                    7) # [REG+IMM], REG
                        [ ! -z "${DSTREG}" ] && [ ! -z "${SRCREG}" ] && \
                        [ ! -z "${DSTIMM}" ] && [   -z "${SRCIMM}" ] && \
                        [ ! -z "${DSTREF}" ] && [   -z "${SRCREF}" ] && ADDR="${index}"
                        ;;
                esac
            done

            ADDR=$(echo "obase=2; ${ADDR}" | bc -q)
            ADDR=$(printf "%.3d" "${ADDR}")
        else
            ADDR="000"
        fi

        ################################################################################
        ##
        ## Set PORT if set on either parameter
        ##
        [ ! -z "${DSTPRT}" ] && DSTPRT=$(echo "${DSTPRT}" | tr -d 'x')
        [ ! -z "${DSTPRT}" ] && PORT=$(echo "obase=2; ibase=16; ${DSTPRT}" | bc)
        [ ! -z "${SRCPRT}" ] && DSTPRT=$(echo "${SRCPRT}" | tr -d 'x')
        [ ! -z "${SRCPRT}" ] && PORT=$(echo "obase=2; ibase=16; ${SRCPRT}" | bc)
        [   -z "${PORT}"   ] && PORT="0"

        PORT=$(printf "%.14d" "${PORT}")

        [ ! -z "${DSTREG}" ] || IMMEDIATE="${DSTIMM}"
        [   -z "${DSTREG}" ] && DSTVAL="0000"
        [ ! -z "${SRCREG}" ] || IMMEDIATE="${SRCIMM}"
        [   -z "${SRCREG}" ] && SRCVAL="0000"
        [ ! -z "${DSTIMM}" ] && IMMEDIATE="${DSTIMM}"
        [ ! -z "${SRCIMM}" ] && IMMEDIATE="${SRCIMM}"

#        [ ! -z "${DSTREG}" ] && debug "DSTREG:    ${DSTREG} (DSTVAL: ${DSTVAL})"
#        [ ! -z "${DSTIMM}" ] && debug "DSTIMM:    ${DSTIMM}"
#        [ ! -z "${DSTREF}" ] && debug "DSTREF:    ${DSTREF}"
#        [ ! -z "${SRCREG}" ] && debug "SRCREG:    ${SRCREG} (SRCVAL: ${SRCVAL})"
#        [ ! -z "${SRCIMM}" ] && debug "SRCIMM:    ${SRCIMM}"
#        [ ! -z "${SRCREF}" ] && debug "SRCREF:    ${SRCREF}"

        ################################################################################
        ##
        ## form the current instruction binary, convert to hexadecimal
        ##
        binary="${opcode[${the_opcode}]}${imm_flag}${DSTVAL}${SRCVAL}${ADDR}${PORT}"
        instruction=$(echo   "obase=10; ibase=2; ${binary}" | bc -q)
        instruction=$(printf "0x%.8X" "${instruction}")

        ############################################################################
        ##
        ## report on the instruction being processed
        ##
        if [ ! -z "${the_opcode}" ]; then
            debug    "======================================================"
            if [ ! -z "${offset}" ]; then
                debug    "offset:        ${offset}"
                debug    "------------------------------------------------------"
            fi
            debug    "the_opcode:    \"${the_opcode}\" (0b${opcode[${the_opcode}]})"
            debug    "------------------------------------------------------"
            debug    "imm_flag:      ${imm_flag}"
            debug    "------------------------------------------------------"
            if [ ! -z "${dst_operand}" ]; then
                debug    "dst_operand:   ${dst_operand}"
                debug    "dst_types:     ${dst_types}"
                debug    "dst_flags:     ${dst_flags}"
            else
                debug    "no dst:        0b0000"
            fi
            debug    "------------------------------------------------------"
            if [ ! -z "${src_operand}" ]; then
                debug    "src_operand:   ${src_operand}"
                debug    "src_types:     ${src_types}"
                debug    "src_flags:     ${src_flags}"
            else
                debug    "no src:        0b0000"
            fi
            debug    "------------------------------------------------------"
            debug    "ADDR:          0b${ADDR}"
            debug    "------------------------------------------------------"
            debug    "PORT:          0b${PORT}"
            debug    "======================================================"
            debug -n "instruction:   ${opcode[${the_opcode}]} ${imm_flag} ${DSTVAL} "
            debug -H "${SRCVAL} ${ADDR} ${PORT}"
            hexalign="${opcode[${the_opcode}]}${imm_flag}${DSTVAL}"
            hexalign="${hexalign}${SRCVAL}${ADDR}${PORT}"
            debug -n "instruction:   "
            for ((index=1; index<=32; index+=4)); do
                let indexend=index+3
                if [ "${index}" -lt 28 ]; then
                    debug -n -H "$(echo ${hexalign} | cut -c${index}-${indexend}) "
                else
                    debug    -H "$(echo ${hexalign} | cut -c${index}-${indexend}) "
                fi
            done
            debug    "------------------------------------------------------"
            debug    "INSTRUCTION:   ${instruction}"
            if [ ! -z "${IMMEDIATE}" ]; then
                debug    "------------------------------------------------------"
                debug    "IMMEDIATE:     ${IMMEDIATE}"
            fi
            debug    "======================================================"
        fi

        ################################################################################
        ##
        ## if not in binary mode, output the hex of the instruction and
        ## any immediate data to STDOUT
        ##
        if [ "${BINARY}" = "false" ] && [ "${VERBOSE}" = "false" ]; then
            [ ! -z "${offset}"      ] && echo    "offset:      ${offset}"
            [ ! -z "${instruction}" ] && echo    "instruction: ${instruction}"
            [ ! -z "${IMMEDIATE}"   ] && echo    "immediate:   ${IMMEDIATE}"
            echo "-----------------------"
        else
            echo "${instruction}"                                       >> ${TMP}
            [ ! -z "${IMMEDIATE}" ] && echo "${IMMEDIATE}"              >> ${TMP}
        fi

        ################################################################################
        ##
        ## if single step is enabled: pause for confirmation
        ##
        [ "${DO_STEP}" = "true" ] && read -e confirmation
        [ "${VERBOSE}" = "true" ] && clear

        ################################################################################
        ##
        ## adjust offset (if offsets are being kept)
        ##
        if [ ! -z "${offset}" ]; then
            offset=$(echo "obase=16; ibase=16; ${offset}+1" | tr -d 'x' | bc)
            if [ ! -z "${IMMEDIATE}" ]; then
                offset=$(echo "obase=16; ibase=16; ${offset}+1" | tr -d 'x' | bc)
            fi
            offset=$(printf "0x%.8X" "0x${offset}")
        fi
    done
done

########################################################################################
##
## remove all generated temporary files
##
rm -f ${TMP} ${LABELSYM} ${BINFILE}

exit 0
